### ISSUE TITLE
Controllo presenza titolo in forum

### ISSUE THREAD

**Issue by Evolve8472** [gianni10049/GDRCD#1]
Può capitare che, aprendo una nuova discussione in forum, qualcuno si dimentichi di inserire il titolo. A quel punto la discussione viene creata comunque ma mostrata nell'elenco senza il titolo e quindi senza il link per accedervi (salvo inserire manualmente l'url nella barra degli indirizzi).
Avere una funzioncina semplice che controlli la presenza del titolo e in caso mando un alert (o un popup sulla casella di inserimento) al momento dell'invio sia molto utile.

**Comment by gianni10049** [comment]
> Può capitare che, aprendo una nuova discussione in forum, qualcuno si dimentichi di inserire il titolo. A quel punto la discussione viene creata comunque ma mostrata nell'elenco senza il titolo e quindi senza il link per accedervi (salvo inserire manualmente l'url nella barra degli indirizzi).
> Avere una funzioncina semplice che controlli la presenza del titolo e in caso mando un alert (o un popup sulla casella di inserimento) al momento dell'invio sia molto utile.

Risolto, inseriti dei required nel html della crazione e della modifica dei post in bacheca, per evitarne direttamente l'inserimento o la modifica in un campo vuoto.

Nel caso in cui dovesse capitare, verra' sosituito dalla scritta "titolo assente".

![image](https://user-images.githubusercontent.com/38789905/113608114-67506380-964a-11eb-9955-ca20b96e7a50.png)
![image](https://user-images.githubusercontent.com/38789905/113608140-720af880-964a-11eb-81cd-c0b0b859d1b6.png)

# commit: 567d5f9ba4b4fbdf1985118ca66b943c7a468df0

**Comment by gianni10049** [comment]
> Può capitare che, aprendo una nuova discussione in forum, qualcuno si dimentichi di inserire il titolo. A quel punto la discussione viene creata comunque ma mostrata nell'elenco senza il titolo e quindi senza il link per accedervi (salvo inserire manualmente l'url nella barra degli indirizzi).
> Avere una funzioncina semplice che controlli la presenza del titolo e in caso mando un alert (o un popup sulla casella di inserimento) al momento dell'invio sia molto utile.

Risolto, inseriti dei required nel html della crazione e della modifica dei post in bacheca, per evitarne direttamente l'inserimento o la modifica in un campo vuoto.

Nel caso in cui dovesse capitare, verra' sosituito dalla scritta "titolo assente".

![image](https://user-images.githubusercontent.com/38789905/113608114-67506380-964a-11eb-9955-ca20b96e7a50.png)
![image](https://user-images.githubusercontent.com/38789905/113608140-720af880-964a-11eb-81cd-c0b0b859d1b6.png)

# commit: 567d5f9ba4b4fbdf1985118ca66b943c7a468df0
