### ISSUE TITLE
Nuovi messaggi

### ISSUE THREAD

**Issue by musicamus4** [gianni10049/GDRCD#12]
Segnalo che la chat dei nuovi messaggi stile WhatsApp non scorre automaticamente verso il fondo, ma resta fissa e bisogna scrollarla manualmente.
Sempre all'interno della schermata dei messaggi potrebbe essere utile inserire un segnalatore che individui le conversazioni che hanno ricevuto un nuovo messaggio, perché al momento non risultano facilmente identificabili.

**Comment by gianni10049** [comment]
Aggiunta la scroll
Aggiunta la grafica per nuovi messaggi (Scritta rossa in bold)

Commit: f514f0b1f5c757475d28dacf34467f33b3b14c60
