### ISSUE TITLE
Mancato aggiornamento dopo eliminazione conversazione

### ISSUE THREAD

**Issue by Kasui92** [gianni10049/GDRCD#14]
Ho notato che se avvio una conversazione, la tengo aperta nel box a destra (_messaggi_box_right_) e poi la elimino completamente, tramite pulsante elimina tutti i messaggi nel box a sinistra, la conversazione rimane ancora aperta nel box a destra (_messaggi_box_right_).

Probabilmente non avviene un aggiornamento di quel contenitore post operazione.

**Comment by gianni10049** [comment]
Aggiunta eliminazione lista messaggi in caso di eliminazione di conversazione visualizzata

Commit: c0c92c0a92dd8a99164e8bc141fe2b56bfe0504f
