### ISSUE TITLE
Nuovi messaggi

### ISSUE THREAD

**Issue by musicamus4** [gianni10049/GDRCD#18]
- Quando apro una conversazione, la finestra dei messaggi si apre al primo messaggio mandato anziché all'ultimo

![Issue1](https://user-images.githubusercontent.com/86823159/124381519-4a681280-dcc3-11eb-873e-1feeea5ff385.png)

- Continua a non scrollare verso il basso (Sparvy ha avuto l'impressione che a lui a volte scrollasse e a volte no, a me non funziona proprio)
- **Non mi mostra i messaggi dell'altra persona finché non invio un mio messaggio** (prima funzionava, deve essere cambiato qualcosa dopo l'ultimo fix)
- Manca la x in alto a destra per chiudere il pannello
- Bisognerebbe evidenziare meglio la conversazione che ha dei messaggi non leggi in sospeso

![Issue2](https://user-images.githubusercontent.com/86823159/124381521-4c31d600-dcc3-11eb-8744-799f05c7a3aa.png)

**Comment by gianni10049** [comment]
La x é una nuova feature e non un bug, la metto nell'apposita lista.

Il resto derivano da mancato aggiornamento delle cache, quindi chiudo lissue per ora e nel caso lo riapriamo se persiste il problema.
