### ISSUE TITLE
Aggiornamento chat

### ISSUE THREAD

**Issue by Jansna** [gianni10049/GDRCD#3]
Diversamente dalla vecchia versione, quando si invia una nuova azione la chat non scrolla fino alla fine del box, ma rimane sulla penultima azione e richiede all'utente di scrollare a mano. Si tratta di una piccolezza, ma può essere scomoda. 

Allego screen: https://prnt.sc/11ddyzj

**Comment by gianni10049** [comment]
Risolto con una funzione nel file /pages/chat/chat_input.js chiamata ScrollDown(), richiamata una volta ad entrata in chat ed ad ogni aggiunta di azione

commit: adad5a01fefdef27312bbd9e210e25264f525aa6
