### ISSUE TITLE
Svuotamento campo tag

### ISSUE THREAD

**Issue by Jansna** [gianni10049/GDRCD#4]
Al momento, inviando un'azione in chat, avviene lo svuotamento automatico del campo tag, diversamente da quel che avviene in molte land e nella vecchia versione 5.5.1, dove il tag viene mantenuto anche dopo l'invio. Si tratta di una piccolezza, ma viene spesso percepita come fastidiosa un po' ovunque.

**Comment by gianni10049** [comment]
Il tag non scompare piu'

Commit: 7b9f8f746c91c9f17fffd8ba98c26029279b10e2
